"""Fix error with dictionary knowledge

Revision ID: f2852cacd8f4
Revises: 1b47f3707523
Create Date: 2022-11-20 20:09:18.504965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2852cacd8f4'
down_revision = '1b47f3707523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_dictionary_knowledge',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('dictionary_content_id', sa.BigInteger(), nullable=False),
        sa.Column('word_knowledge', sa.Integer(), server_default='0', nullable=True),
        sa.ForeignKeyConstraint(['dictionary_content_id'], ['dictionary_content.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['bot_user.id'], ),
        sa.UniqueConstraint("user_id", "dictionary_content_id"),
        sa.PrimaryKeyConstraint('id')
    )

    op.drop_column('dictionary_content', 'word_knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('dictionary_content', sa.Column('word_knowledge', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, default=0))
    op.drop_table('user_dictionary_knowledge')
    # ### end Alembic commands ###
